FROM "mcr.microsoft.com/devcontainers/base:jammy"
# Install Node 16 and NPM
RUN sudo apt-get install curl \
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - &&\
sudo apt-get install nodejs \