name: Branches CI

on:
  pull_request:
    types: 
      - opened
      - synchronize
    branches:
      - main

jobs:
  ci-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run CI Tasks
        run: yarn ci

      - name: Vitest Coverage Report
        uses: davelosert/vitest-coverage-report-action@v1.3.2
        with:
          json-summary-path: ./packages/cli/src/coverage/coverage-summary.json
          json-final-path: ./packages/cli/src/coverage/coverage-final.json
          vite-config-path: ./packages/cli/vite.config.ts

      - run: |
          cd packages/cli/src/

      - name: Update Coverage Badge
        uses: we-cli/coverage-badge-action@main
